### ISSUE TITLE
Could you please share the transcript files

### ISSUE THREAD

**Issue by Thien223** [homink/speech.ko#2]
Thank for your sharing. 

There are problems with your respository, so I cannot run the run.sh file. 

Anyway, I can download the file from home page (the links you have shared)
But I could not find the transcript files. Could you please share them to me? Or give me download links?

I appreciate your helps. Thank you so much..

**Comment by homink** [comment]
When you unzipped the downloaded corpus, you should have script_nmbd_by_sentence.txt which is a transcription file. If you don't find it, that means you have not downloaded all zip files.

**Comment by tdplaza** [comment]
Yes. as I have said, there is problems so I could not run your download script.

I downloaded audio file on the website, and could not find the transcript. 

Could you please share it directly to me? Thank for your helps

**Comment by Thien223** [comment]
Yes. 

I downloaded audio files on the website, and could not find the transcript file there.

Could you please share it directly to me, or just give me the download link? Thank for your helps

**Comment by Thien223** [comment]
Thank you @homink, I have found it. It is located in one of the folders. Thank you.
