### ISSUE TITLE
There may be some changes in database.

### ISSUE THREAD

**Issue by crapas** [homink/speech.ko#3]
Thank you for making this tools.

There is a question. When I downloaded  the database from NIKL, I found that there were 87453 files but, your script check that there are 87407.

Q1. Is there as version difference in database?
Q2. If the database changed, how can I fix it?

**Comment by homink** [comment]
Q1. I don't think so. There is no corpus posting date change in the NIKL webpage. I recommend you to try again after deleting all of thm.

Q2. There are 2 steps for the correction.

1. Audio file name correction : https://github.com/homink/speech.ko/blob/094d93d075507aef4a7ee88e1e56928ca4d97cfd/run.sh#L140
    You will be able to follow the way I did.

2. Matching audio file with transcriptions
https://github.com/homink/speech.ko/blob/094d93d075507aef4a7ee88e1e56928ca4d97cfd/run.sh#L164
    This requires Korean listening so that you can check which audio file belongs to which transcription.
