### ISSUE TITLE
Cannot download files

### ISSUE THREAD

**Issue by JRMeyer** [homink/speech.ko#4]
I see the following error when I click on the first link to download the files:

```
 서비스 이용에 불편을 드려 죄송합니다.

서버 프로그램에서 예상치 못한 오류가 발생하여 해당 페이지를 열람할 수 없습니다.
자세한 사항은 홈페이지 관리자에게 문의 바랍니다.
```

**Comment by homink** [comment]
It reads "not available for downloading for now. Ask the web administrator". They seem to be not downloadable for some reason.

**Comment by JRMeyer** [comment]
Do you have time to reach out and see if the issue is fixable? Do you know of a mirror?

**Comment by homink** [comment]
https://ithub.korean.go.kr/user/corpus/referenceManager.do

You will be able to download from the above link although you will be required to provide some information like Korean mobile phone number for the identification process.
